OAuth2.gs, Service.gs, Utilities.gs
=> Setting the Accepts HTTP header on token requests based on the token format.

src/Service.gs
This could have been quite ugly, if this assignment were at another place.
Aren't any static code analysis tools used in the publication workflow of these libraries? I found this bug with ESLint. Especially with regard to authentication libraries, code quality needs to be high.
=> Fixed assignment in if expression

src/OAuth2.gs
The dist task uses gulp-expose, which should create a modules variables. The typeof test allows to stay the code unchanged after the dist task
=> typeof test of a gulp-expose varables

dist/OAuth2.gs, samples/Medium.gs, samples/Strava.gs, src/Service.gs
I tried using this library to connecting Google Apps Script and the [Medium API](https://github.com/Medium/medium-api-docs), and `getTokenFromResponse_` throws an error despite getting a successful response. The function currently throws an error if the response code isn't 200, but successful access token response from Medium have a 201 status code. So I modified that check to throw an error if the status code is outside of the entire 2xx success range.
This PR also includes examples for connecting to [Strava](https://strava.github.io/api/) and Medium.
=> Fix Bug in `getTokenFromResponse_` for APIs that Respond with 201 Created

src/Service.gs
I moved to public `Service.prototype.getToken_`.
I also commited package-lock.json file and build a new dist https://stackoverflow.com/questions/44206782
Should I split this into two pull requests?
=> Unprivate Service.prototype.getToken_

src/Service.gs
If a cache is set then a token is acquired it is stored in both the Cache service and the Properties service. Therefore, when the Service is reset the token must be removed from the Cache service as well as the Properties service. Otherwise, getAccessToken() would still return the cached token after a call to reset().
=> Upon service reset, also clear the cached token

package-lock.json, samples/Salesforce.gs
Addresses #115. The sample wasn't requesting a refresh token and wasn't able to handle the dynamic session invalidation that Salesforce uses.
=> Updating Salesforce sample

src/Storage.js, test/test.js
When no value is found in the storage for a given key, cache that "null" in the memory and CacheService to reduce hits on the PpropertiesService for future runs. Fixes #144.
=> Cache null values in storage

src/Service.js, src/Storage.js, test/mocks/lock.js, test/test.js
Previously locking was done for every call to `hasAccess()`, which was overly aggressive. Instead this has been replaced by only locking when the token is expired, and re-loading the token to check if it's still expired. Fixes #143.
=> Reduce unnecessary usage of LockService

README.md, src/Service.js, src/Utilities.js, test/mocks/script.js, test/test.js
=> Add support for custom callback parameters.

samples/Add-on/Code.gs, samples/AdobeSign.gs, samples/Basecamp.gs, samples/ChatWork.gs, samples/CloudIdentityAwareProxy.gs, samples/Dropbox.gs, samples/Facebook.gs, samples/FitBit.gs, samples/GitHub.gs, samples/GooglePlus.gs, samples/Harvest.gs, samples/Jira.gs, samples/LinkedIn.gs, samples/Medium.gs, samples/Meetup.gs, samples/RingCentral.gs, samples/Salesforce.gs, samples/Smartsheet.gs, samples/Strava.gs, samples/UltraCart.gs, samples/VK.gs, samples/WebApp/Code.gs, samples/Wordpress.gs, samples/Yahoo.gs, samples/Yandex.gs, samples/Zendesk.gs, samples/Zoom.gs, samples/eBay.gs, src/OAuth2.js, src/Service.js
Needed for the OAuth provider eBay, which requires you to register redirect URI pairs ahead of time and reference the pair by ID. Fixes #156.
=> Allow for arbitrary redirect URIs.

src/Service.js
Some IDPs such as OpenAM can be configured to provide both an access_token and an id_token with the callback.  This update provides a function that can be called to return the id_token instead of the access_token.  The id_token contains a payload with claims related to the authenticated identity.  This was required for API integration to Service Now, who told me their service cannot be configured to accept an access_token.
=> Add function to return id_token (for Service Now)

README.md
Current README.md still mention approval_prompt that is not valid anymore.
Also, prompt=consent param is required in some situation (if user already approved an app) to have a refresh token returned when exchanging authorization code.
Also mentions Session.getEffectiveUser().getEmail() as an alternative to Session.getActiveUser().getEmail() in login_hint when used in add-on triggers (prevents a warning message on every execution).
=> Update example for Google OAuth2 offline access

samples/Mailchimp.gs
I have included support for Mailchimp in my [Mail Merge with Attachments](https://gsuite.google.com/marketplace/app/mail_merge_with_attachments/223404411203) add-on for Gmail using the OAuth2 Library for Google Apps Script.
To get started, create your own set of credentials from your Mailchimp account as described [here](https://mailchimp.com/developer/guides/how-to-use-oauth2/#Step_1%3A_Register_your_application).
- In your Mailchimp account, navigate to the Account page.
- In the drop-down menu, select Extras, and then Registered Apps.
- Click Register an App.
- In the appropriate fields, enter your application information and click Create.
=> Mailchimp API with Google Apps Script

README.md, package-lock.json, src/Service.js, src/Storage.js, test/test.js
There are use cases where persisting tokens isn't required, and doing so exceeds the `PropertiesService` write quota. Permit services which don't set a properties store, and update the README to clarify the usage.
Fixes #217.
=> Don't require token storage in properties

src/Utilities.js
Alternatively, use a primitive type instead of nullable boxed type.
=> Add non-nullable modifier to return type of functions never returning null

package.json, src/Service.js, src/Storage.js, test/mocks/properties.js, test/test.js
Also changed the in-memory storage to use prefixed keys, to be consistent with properties and cache (since it caused me a lot of confusion while developing this feature). Fixes #229.
=> Remove all values from storage when the service is reset

README.md
=> Add FAQ for multiple services.

README.md, src/OAuth2.js, src/Service.js, test/test.js
=> Add ability to list service names.

README.md
Fix the empty link to Smartsheet API docs
```sh
FILE: ./README.md
[✓] https://travis-ci.org/googleworkspace/apps-script-oauth2
[✓] https://travis-ci.org/googleworkspace/apps-script-oauth2.svg?branch=master
[✓] https://developers.google.com/apps-script/reference/script/state-token-builder
[✓] https://developers.google.com/apps-script/reference/calendar/
[✓] https://developers.google.com/apps-script/advanced/admin-sdk-directory
[✓] https://developers.google.com/apps-script/concepts/manifests#editing_a_manifest
[✓] https://developers.google.com/apps-script/concepts/scopes#setting_explicit_scopes
[✓] https://developers.google.com/apps-script/reference/script/script-app#getoauthtoken
[✓] samples/NoLibrary
[✓] dist
[✓] samples/Add-on/Callback.html#L47
[✓] …
```
=> fix an readme empty link

samples/LinkedIn.gs
Linkedin has started [requiring](https://docs.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow#step-2-request-an-authorization-code) the scope to be passed in with the request. The People V1 API requires the [r_network](https://developer.linkedin.com/docs/v1/people/connections-api) scope. This change adds it to the authentication flow.
=> add scope to linkedin example

samples/Twitter.gs
Makes use of Twitter API v2 along with OAuth 2.0 for Making requests on behalf of users — https://developer.twitter.com/en/docs/authentication/oauth-2-0/user-access-token
=> Adding Twitter.gs

samples/Twitter.gs
Use the `setParam` method of the OAuth2 library to add parameters. Cleaner code!
=> Add pkce parameters in the authorization url

src/OAuth2.js
=> Updated JSDoc syntax for better type suggestions  In  getRedirectUri Function

samples/Onshape.gs
Onshape developer portal (documentation & application registration): https://dev-portal.onshape.com/
This is my first real pull request on GitHub, so please let me know if I'm doing anything wrong! I signed the Google CLA. Let me know if there's anything else I should do.
=> Add sample for Onshape

samples/Google.gs
Current version sample Google.gs not return refresh_token on request. I.e. always refresh_token=null.
A similar issue:  https://github.com/googleapis/google-api-dotnet-client/issues/1185
=> Update Google sample

package.json
As a developer building a GAS project using ES modules (import/export), I would like to be able to `import` this package:
```
import { OAuth2 } from 'OAuth2';
```
Currently, this fails with an error like so:
```
Module not found: Error: Can't resolve 'OAuth2' in '/Users/nathan/.../src'
Field 'browser' doesn't contain a valid alias configuration
```
After declaring an entry-point for this package (via package.json), then I am able to `import` the package without error.
=> Adds entrypoint

src/Service.js
This is referenced in some OAuth documentation including:
* https://www.ibm.com/docs/en/api-connect/2018.x?topic=settings-configuring-timeouts-access-tokens-refresh-tokens
This PR doesn't update the dist/* files. This is a proposal at this point and I'd be happy to add changes to the dist file if it's needed.
=> Add support for refresh_expires_in

samples/Dropbox.gs
See the [Dropbox OAuth documentation](https://developers.dropbox.com/oauth-guide#:~:text=Note%3A%20you%E2%80%99ll%20need%20to%20include%C2%A0token_access_type%3Doffline%20as%20a%20parameter%20on%20your%20Authorization%20URL%20in%20order%20to%20return%20a%20refresh_token%20inside%20your%20access%20token%20payload.). Fixes #434.
=> Fix issue with refresh tokens in the Dropbox sample

samples/Twitter.gs
Use library's builtin code verifier capability
=> Update Twitter sample

dist/OAuth2.gs, src/Service.js, test/test.js
Fix for https://github.com/googleworkspace/apps-script-oauth2/issues/506
**Problem**: The support for PKCE (Proof Key for Code Exchange) was introduced in the library, making the `client_secret` field optional (see commit [e6afdfb](https://github.com/googleworkspace/apps-script-oauth2/commit/e6afdfb52d613f4e99002bf72228b32a7299cfc7)). However, the `client_secret` field is still included in the list of validated fields in the `refresh()` method ([Service.js#L667](https://github.com/googleworkspace/apps-script-oauth2/blob/main/src/Service.js#L667)).
**Issue**: When creating a client without setting a `client_secret` (using PKCE for authentication), the token cannot be refreshed after its default expiration of one hour. This is because the validation check in the `refresh()` method expects a …
=> fix: issue with refreshing token when client_secret is not set
